name: Java CI

on:
  push:
    tags:
      - 'dev**'
      - 'staging**'
      - 'prod**'
    branches:
      - master

env:
  CONTAINER_REGISTRY: harbor.bratislava.sk
  IMAGE_PATH: standalone
  NAMESPACE: magproxy

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_VERSION: 0.1-SNAPSHOT
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Setup Maven
        run: |
          mvn --version
          # This step is a workaround to avoid a decryption issue of Spotify's
          # com.spotify.dockerfile-maven plugin and github's provided maven
          # settings.xml file
          rm ~/.m2/settings.xml

      - name: Build with Maven
        run: |
          mvn clean package

  conditions:
    name: Check for cluster conditions
    uses: bratislava/github-actions/.github/workflows/cluster-deploy-conditions.yml@stable

  deploy-dev:
    name: Deploy to DEV
    if: needs.conditions.outputs.dev == 'true'
    needs: [conditions, build]
    uses: bratislava/github-actions/.github/workflows/deploy-with-bratiska-cli.yml@stable
    with:
      cluster: tkg-innov-dev
      url: https://tkg.dev.bratislava.sk
      debug: --debug
      version: beta
      directory: "."
      
    secrets:
      service-account: ${{ secrets.DEV_STANDALONE_TOKEN }}
      registry-pass: ${{ secrets.HARBOR_REGISTRY_PASSWORD }}
      sentry-token: ${{ secrets.SENTRY_AUTH_TOKEN }}

  deploy-staging:
    name: Deploy to STAGING
    if: needs.conditions.outputs.staging == 'true'
    needs: [conditions, build]
    uses: bratislava/github-actions/.github/workflows/deploy-with-bratiska-cli.yml@stable
    with:
      cluster: tkg-innov-staging
      url: https://tkg.staging.bratislava.sk
      debug: --debug
      flag: --staging
      namespace: ${NAMESPACE}
      directory: "."
    secrets:
      service-account: ${{ secrets.STAGING_STANDALONE_TOKEN }}
      registry-pass: ${{ secrets.HARBOR_REGISTRY_PASSWORD }}
      sentry-token: ${{ secrets.SENTRY_AUTH_TOKEN }}

  deploy-prod:
    name: Deploy to PROD
    if: needs.conditions.outputs.prod == 'true'
    needs: [conditions, build]
    uses: bratislava/github-actions/.github/workflows/deploy-with-bratiska-cli.yml@stable
    with:
      cluster: tkg-innov-prod
      url: https://tkg.bratislava.sk
      flag: --production
      namespace: ${NAMESPACE}
      directory: "."
    secrets:
      service-account: ${{ secrets.PROD_STANDALONE_TOKEN }}
      registry-pass: ${{ secrets.HARBOR_REGISTRY_PASSWORD }}
      sentry-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
